#!/usr/bin/env bash

set -euo pipefail

echo "Use print-epub.sh instead."

# if [ $# -ne 1 ]; then
#   >&2 echo "usage: $0 <input.epub>"
#   exit 1
# fi
#
# if ! command -v ebook-convert &> /dev/null; then
#   >&2 echo "This script requires Calibre command line tools."
#   >&2 echo "→ https://calibre-ebook.com/"
#   exit 1
# fi
#
# ebook-convert "$1" ".pdf" \
#   --pdf-page-margin-bottom=48.0 \
#   --pdf-page-margin-top=48.0 \
#   --pdf-page-margin-right=48.0 \
#   --pdf-page-margin-left=144.0 \
#   --pdf-serif-family="Garamond Premier Pro" \
#   --pdf-sans-family="Gill Sans" \
#   --pdf-mono-family="Menlo" \
#   --pdf-default-font-size=16 \
#   --pdf-mono-font-size=14 \
#   --custom-size="7.75x10.25" \
#   --unit=inch \
#   --preserve-cover-aspect-ratio

# optional: Try tweaking --input-profile and --output-profile
# optional: --pdf-hyphenate
# todo: might be nice to find a way to upscale images with machine learning
