#!/usr/bin/env bash

set -euo pipefail

# ----- logging & colors -------------------------------------------------- {{{

red=$'\x1b[0;31m'
green=$'\x1b[0;32m'
yellow=$'\x1b[0;33m'
cyan=$'\x1b[0;36m'
cnone=$'\x1b[0m'

USE_COLOR=
if [ -t 1 ]; then
  USE_COLOR=1
fi

# Detects whether we can add colors or not
in_color() {
  local color="$1"
  shift

  if [ -z "$USE_COLOR" ]; then
    echo "$*"
  else
    echo "$color$*$cnone"
  fi
}

success() { echo "$(in_color "$green" "[ OK ]") $*"; }
error() { echo "$(in_color "$red" "[ERR!]") $*"; }
info() { echo "$(in_color "$cyan" "[ .. ]") $*"; }
fatal() { error "$@"; exit 1; }
# Color entire message to get users' attention (because we won't stop).
attn() { in_color "$yellow" "[ .. ] $*"; }

# }}}

# ----- helper functions ------------------------------------------------------

usage() {
  cat <<EOF

git-rebase-stack: TODO Name and description

Usage:
  git-rebase-stack [options] TODO incantations

Arguments:
  TODO Required (positional) arguments

Options:
  TODO optional flags

EOF
}

expect_two_args() {
  if [ "$2" = "" ]; then
    error "Missing argument to $1"
    usage
    exit 1
  fi
}

# ----- option parsing --------------------------------------------------------

orig_onto=
orig_head=
orig_from=
do_push=

while [[ $# -gt 0 ]]; do
  case $1 in
    --onto)
      expect_two_args "$1" "${2:-}"
      orig_onto="$2"
      shift 2
      ;;
    -h|--head)
      expect_two_args "$1" "${2:-}"
      orig_head="$2"
      shift 2
      ;;
    -f|--from)
      expect_two_args "$1" "${2:-}"
      orig_from="$2"
      shift 2
      ;;
    -p|--push)
      do_push="1"
      shift
      ;;
    *)
      error "Unrecognized argument: $1"
      usage
      exit 1
      ;;
  esac
done

# ----- defaulting ------------------------------------------------------------

if [ "$orig_onto" = "" ]; then
  orig_onto="origin/master"
fi

echo 'here 1'

if [ "$orig_head" = "" ]; then
  if git merge-base --is-ancestor HEAD "$orig_onto"; then
    error "You are on a commit that is already merged into origin/master."
    info  "Check out any commit on the stack you want to rebase."
    exit 1
  fi
echo 'here 2'

  independent_branches=()
  while IFS= read -r line; do
    # Will show two branch names if two branches are at the same commit
    independent_branches+=( "$(git for-each-ref --points-at "$line" --format="%(refname:short)" "refs/heads/*")" )
  done < <(git show-branch --independent)
echo 'here 3'

  if [ "${#independent_branches[@]}" -eq 0 ]; then
    fatal "Did not find any branches"
  fi
echo 'here 4'

for branch in "${independent_branches[@]}"; do
echo "- $branch"
done

echo 'after 4'

  potential_heads=()
  for branch in "${independent_branches[@]}"; do
    if git merge-base --is-ancestor HEAD "$branch"; then
      potential_heads+=( "$branch" )
    fi
  done
echo 'here 5'

  if [ "${#potential_heads[@]}" -eq 0 ]; then
    fatal "No branches contain HEAD. Is it orphaned?"
  fi

  if [ "${#potential_heads[@]}" -gt 1 ]; then
    error "Multiple stack heads can reach the current commit:"
    for potential_head in "${potential_heads[@]}"; do
      info "- $potential_head"
    done
    info  "This script doesn't yet support this scenario"
    info  "Please share with @jez the output of this command:"
    info $'    git log --graph --oneline --decorate --branches="*$USER*" --remotes="*$USER*" master origin/master'
    info $'(replacing $USER with whatever you prefix your branches with, if not your username)'
    info
    info  "In the mean time, please provide a branch to re-stack manually, with --head <branch>"
    exit 1
  fi

  orig_head=${potential_heads[0]}
fi

info "Rebasing stack starting from $orig_head onto $orig_onto"

# ----- main ------------------------------------------------------------------

merge_base="$(git merge-base "$orig_head" "$orig_onto")"

echo "$merge_base"

if git merge-base --is-ancestor "$orig_head" "$orig_onto"; then
  error "You are on a commit that is already merged into origin/master."
  info  "Check out any commit on the stack you want to rebase."
  exit 1
fi

exit 0

# TODO(jez) Completely remove orig_from, replace with first branch above merge_base
# (error if there is only one branch, because that's orig_head)
# if [ "$orig_from" = "" ]; then
#   orig_from="$(git merge-base "$orig_head" "$orig_onto")"
# fi

if [ "$orig_from" = "$orig_head" ]; then
  error "Nothing to rebase."
  exit 1
fi

# Check if command output is non-empty
if [ "$(git rev-list --merges "$orig_from..$orig_head" | head -c1 | wc -c)" != "0" ]; then
  error "There are merge commits between $orig_from and $orig_head."
  error "Merge commits are not supported."
  exit 1
fi

# -----------------------------------------------------------------------------

# List commits from orig_from to orig_head, not including orig_from.
commits=()
while IFS= read -r line; do
  commits+=( "$line" )
done < <(git rev-list --reverse "$orig_from..$orig_head")

echo "${commits[@]}"

# List branches that point directly to one of these commits, in order
branches=()
for commit in "${commits[@]}"; do
  while IFS= read -r line; do
    branches+=( "$line" )
    # TODO(jez) This could be slow, especially without http://go/gitfetch
  done < <(git for-each-ref --points-at "$commit" --format="%(refname:short)" "refs/heads/*")
done
echo "${branches[@]}"

onto="$orig_onto"
from="$orig_from"
for branch in "${branches[@]}"; do
  branch_sha=$(git rev-parse --short "$branch")

  rebase_cmd=("git" "rebase" "--quiet" "--onto" "$onto" "$from" "$branch")
  info "${rebase_cmd[*]}"
  "${rebase_cmd[@]}"

  onto="$branch"
  from="$branch_sha"
done

success "All branches rebased."

if [ "$do_push" != "" ]; then
  for branch in "${branches[@]}"; do
    push_cmd=("git" "push" "--force-with-lease" "--quiet" "origin" "$branch")
    info "${push_cmd[*]}"
    "${push_cmd[@]}"
  done

  success "All rebased branches pushed."

  # TODO(jez) This is all wrong; they shouldn't all be based on master but instead the previous one.
  # if [ "$do_land" != "" ]; then
  #   for branch in "${branches[@]}"; do
  #     # TODO(jez) This doesn't check for `hub` / `ghi` being available
  #     info "Getting PR number for branch $branch"

  #     if [ "$(hub pr list -h "$branch" | head -c1 | wc -c)" = "0" ]; then
  #       warn "No PR open for $branch"
  #       continue
  #     fi

  #     pr_url="$(hub pr show -u -h "$branch")"
  #     pr_number="${pr_url##*/}"

  #     ghi_edit_cmd=("ghi" "edit" "$pr_number" "-H" "$branch" "--base" "master")
  #     info "${ghi_edit_cmd[*]}"
  #     "${ghi_edit_cmd[@]}"
  #   done

  #   success "Updated all PR branches"
  # fi
fi

# TODO(jez) `git-land` == `git-rebase-stack --from`
# Might also want to delete the landed branch locally and remotely
#
# hub api -X POST /api/v3/repos/stripe-internal/pay-server/issues/209764/comments -F body=mergebot-submit
#
# ^ Deleting a branch will close stacked PRs, so probably want something that
#   edits the landed branch's PR base
#   url=$(git pr show -u); pr_number=${url##*/}; echo "$pr_number"; ghi edit "$pr_number" --base master
#   curl --netrc -XPATCH "https://api.github.com/repos/sorbet/sorbet/pulls/$pr_number" -H "Content-Type: application/json" -d '{"base": "master"}'

# vim:fdm=marker
