#!/bin/bash

#
# Given a text file like
#
#   foo.txt:3
#   bar/qux.rb:17
#
# and a sed expression like `s/old/new/`, run the expression in place on all
# the mentioned files + line combinations.
#
# Examples:
#
#   multi-sed locs.txt 's/\*\([A-Za-z0-9_][A-Za-z0-9_]*\)/*T.unsafe(\1)/'
#
#   (Replaces things like `*foo` with `*T.unsafe(foo)` only on mentioned lines.)
#
#   multi-sed - 's/\*\([A-Za-z0-9_][A-Za-z0-9_]*\)/*T.unsafe(\1)/'
#
#   (Same as above, but reads locs from stdin)
#


if [ $# -lt 2 ]; then
  echo "usage: multi-sed <locs.txt> s/<find>/<replace>/ [sed options]"
  echo '  where <locs.txt> has lines like file.ext:20'
  echo '  use - for <locs.txt> to read from stdin'
  exit 1
fi

LOCS_FILE="$1"
shift
SUBSTITUTION="$1"
shift

if [ "$LOCS_FILE" = "-" ]; then
  LOCS_FILE=/dev/stdin
fi

while read -r file_line; do
  # shellcheck disable=SC2206
  pair=(${file_line//:/ })

  file=${pair[0]}
  line=${pair[1]}

  sed -i.bak "$@" "$line$SUBSTITUTION" "$file"
  rm "$file.bak"
done < "$LOCS_FILE"
