#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF
new-remote [options] <box-name>

Options:
    --skip-new   Assume <box-name> already exists, only run the dotfiles setup
    --skip-ssh   Don't SSH into the box after all other work
EOF
}

skip_new=false
skip_ssh=false
workspace=pay-server

box_name=
while [[ $# -gt 0 ]]; do
  case $1 in
    --skip-new)
      skip_new=true
      shift
      ;;
    --skip-ssh)
      skip_ssh=true
      shift
      ;;
    --workspace)
      workspace=$2
      shift
      shift
      ;;
    -h|--help)
      usage
      exit
      ;;
    *)
      if [ "$box_name" = "" ]; then
        box_name="$1"
        shift
      else
        >&2 usage
        exit 1
      fi
      ;;
  esac
done

if ! $skip_new; then
  pay remote new "$box_name" --repo stripe-internal/mint --workspace "$workspace" --no-open-code --no-notify-on-ready --skip-confirm
fi

pay box map-ssh

if ! $skip_new; then
  ssh "$box_name" -- "cd /pay/src && git checkout HEAD~0 && git branch -D '$box_name'"
fi

# shellcheck disable=SC2016
rsync --perms --chmod 600 "$HOME/.config/hub-mydev" "$box_name":'~/.config/hub'

# Otherwise we can't get to github.com
ssh "$box_name" -- mkdir -p '"$HOME/.ssh"'
# shellcheck disable=SC2016
scp "$HOME/.ssh/config-mydev" "$box_name":'~/.ssh/config'

# Now that we can get to github.com, clone dotfiles.
ssh "$box_name" -- git clone '--jobs="$(nproc)"' --recursive git@github.com:jez/dotfiles.git '$HOME/.dotfiles'
ssh "$box_name" -- git clone '--jobs="$(nproc)"' --recursive git@github.com:jez/bin.git '$HOME/bin'
ssh "$box_name" -- git clone '--jobs="$(nproc)"' --recursive git@git.corp.stripe.com:jez/livegrep-cli.git '$HOME/livegrep-cli'

ssh "$box_name" -- 'cd "$HOME/.dotfiles" && ./devbox-setup.sh'

ssh "$box_name" -- 'ln -v -s /pay/src/pay-server ps'
ssh "$box_name" -- 'cd "$HOME/bin" && ln -v -s "$HOME/livegrep-cli/lg" .'

osascript "-e" "display notification \"Your new remote devbox \`$box_name\` is ready for use\" with title \"Remote devbox ready\""

if ! $skip_ssh; then
  # -t == force tty allocation
  exec ssh -t "$box_name" "zsh --login --interactive -c 'cd /pay/src/$workspace && mux'"
fi

# TODO(jez) Figure out where to put pay configure --no-pay-up-emoji
