#!/usr/bin/env bash

# Get paths where source files are located. http://stackoverflow.com/a/42918
ROOTDIR="$(dirname "$(perl -MCwd -le 'print Cwd::abs_path(shift)' "${BASH_SOURCE[0]}")")"

if [ $# -eq 0 ]; then
  jrnl -from today --export json
else
  jrnl "$@" --export json
fi | \
  jq -r -f "$ROOTDIR/viewjrnl.jq" | \
  less -F -X
