#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<EOF

vimpay: Open file from pay test command

Usage:
  vimpay test <file>:<line>

Environment:
  EDITOR      The Vim editor to launch. [default: vim]

Intended usage is to type:
  vim<Cmd-V>
after copying a clicking "Copy command to clipboard" in a CIBot build result.

EOF
}

if [ $# -ne 2 ]; then
  usage
  exit 1
fi

exec viml "$2"
