#!/usr/bin/env bash

# Usage:
#   Take any `rg` invocation and replace the `rg` with `vimrg`
#   Should work with flags like -g and -t, etc.
#   Assumes that the search pattern is last (shouldn't fail if that's not the
#   case, but will set Vim's search register to the value of the last argument)
#
# Requires GNU printf

${EDITOR:-vim} -c ":Grepper -query $(env printf ' %q' "$@")" -c ":let @/='${!#}'"
