#!/bin/bash

# jif [[-n "$1" -o -n "$2" -o -n "$3"]]
if [ $# -le 1 ]
then
  echo "usage: wget_offline <initial-directory>"
  exit
fi

wget \
  --recursive \
  --no-clobber \
  --page-requisites \
  --html-extension \
  --convert-links \
  --restrict-file-names=windows \
  --no-parent \
  "$3"
